### PR TITLE
gets basic data from meetup api.

### PR DESCRIPTION
**Pull request by wisteria-hill-technologies**
Hi, all!

I have added basic GET JSON-P calls to meetup api to fetch some data.  It works. 
Please feel free to run it on your machine, and check.
If ok, please give OK to pull it to master.  If I do not hear from anyone, I will pull it tomorrow.

Mark, please feel free to make your own branch, and change and style the site with bootstrap.

Anybody, please feel free to contribute if you have time.

Cheers,
Noby

### CODE REVIEW

**Comment by markhorsell** [comment]
Hi, yes go ahead, i'm working on my own github for now, just following the tutorial. I expect ill branch from this next week sometime.

**Comment by markhorsell** [comment]
oh and nice work :)

**Comment by markhorsell** [comment]
Hi Noby,
I don't have permission to create my own branch. How would you like to do this? Do you want to create a branch for me and ill make pull requests? Or something else?

**Comment by markhorsell** [comment]
add to that, Jekyll isnt supported on windows! which is what i use at home. Have tried setting it up but its not looking very promising. I guess you're using a mac?

**Comment by wisteria-hill-technologies** [comment]
Hi, Mark sorry didn't know.  Let me check.

**Comment by markhorsell** [comment]
its possible, in fact i have it installed via https://davidburela.wordpress.com/2015/11/28/easily-install-jekyll-on-windows-with-3-command-prompt-entries-and-chocolatey/
but its not working , it seems to compile ok and i can run jekyll serve without complaints but it doesnt update! I can probably get enough done on the mac during lunchtimes for now

**Comment by markhorsell** [comment]
ok i have something working, a bit clunky but should be ok

**Comment by wisteria-hill-technologies** [comment]
Hi, Mark
Yes, I am using Mac for this.  I may try with windows later.  
Regarding the branch creation, I changed your access level, so you should be able to push, pull, create branches now.  Also, easier to use https than ssh.  Please have a go at creating another branch and push it up to the repo.
Thank you,
Noby

**Comment by markhorsell** [comment]
that's great, i have access now :). I've solved the windows issue too, so
i'm good to go. I'm liking Jekyll so far. Hopefully ill have some time on
wednesday to make some updates. thanks

**Comment by wisteria-hill-technologies** [comment]
thank you

**Pull request merged**
